app:
  image: ibmcom/swift-ubuntu
  ports:
    - "8090:8090"
  volumes:
    - .:/root/SwiftEnterpriseDemo
  command: bash -c "cd /root/SwiftEnterpriseDemo && swift build --clean && swift build && ./.build/debug/DemoAppServer"
