app:
  image: ibmcom/swift-ubuntu
  ports:
    - "8090:8090"
  volumes:
    - .:/root/swift-enterprise-demo
  command: bash -c "cd /root/swift-enterprise-demo && swift build --clean && swift build && ./.build/debug/Server"
